name: On Merge - Native - Builder Substrate

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - .github/workflows/**
      - native/**
      - Makefile

jobs:
  build-push:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, neoverse-n1]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Docker Image
        run: |

          # Login for images push
          echo ${{ secrets.DANGER_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Build & push
          make
  build-push-cleanup:
    if: github.event.pull_request.merged == true
    needs: [build-push]
    runs-on: [self-hosted, neoverse-n1]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Clean Dangling images
        run: |

          # Delete all dangling packages org-wide, this is because this repo has epoch worker!
          gi-gh-container-cleaner --organization=${{ github.repository_owner }} --pat=${{ secrets.DANGER_TOKEN }}
