name: On PR - Native - Builder Substrate

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - native/**
      - Makefile

jobs:
  build-check:
    runs-on: [self-hosted, neoverse-n1]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test Build Docker Image
        run: make check
