name: On PR - Native - Builder Substrate

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - native/**
      - Makefile

jobs:
  build-check-arm64:
    runs-on: [self-hosted, neoverse-n1]
    steps:
      - uses: actions/checkout@v3
      - name: Test Build Docker Image
        run: make check
  build-check-x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Build Docker Image
        run: make check
